defmodule MyApp.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :user_id, :uuid
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :public, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :body, :text, null: false
    end

    create table(:tweets, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :email, :text, null: false
    end

    alter table(:users) do
      modify :user_id, references(:tweets, type: :uuid, column: :id, name: "users_user_id_fkey")
    end
  end

  def down do
    alter table(:users) do
      modify :user_id, :uuid
    end

    drop table(:tweets)

    drop table(:users)
  end
end